OpenAPI spec
flopezag/SDM.SQLgeneration pull request #1
Opened 2024-02-07 17:12 UTC by feki-rihab

2024-02-07 18:01 UTC, flopezag requested changes

2024-02-07 18:01 UTC, flopezag commented on README.md
>  Python Server to generate a SQL Schema based on the model description of a Smart Data Model
Python Server to generate a SQL Schema based on the model description of a Smart Data Model.

2024-02-07 18:01 UTC, flopezag commented on README.md
> +Please note that this is a python 3.11 project, to install it chech this [link](https://www.python.org/downloads/).
to install it, check this

2024-02-07 18:01 UTC, flopezag commented on README.md
> +
Add a note to explain how to leave the shell

2024-02-07 18:01 UTC, flopezag commented on README.md
> +  -h, --host HOST     launch the server in the corresponding host
This is a problem of copy/paste -i -o, they are wrong. I suggest changing for the moment -i description to specify the file to the script and -o generate the corresponding output file

2024-02-07 18:01 UTC, flopezag commented on README.md
> +The `SDMQualityTesting` schema is also defined in the components section.
You need to specify what is a schema because the sentence is not clear about what are you talking about.

2024-02-07 18:01 UTC, flopezag commented on api/server.py
> +__version__ = "0.1.0"
Maybe this line is not needed anymore...

2024-02-07 18:01 UTC, flopezag commented on doc/openapi.yaml
> +  description: FastAPI application for SDM Quality Testing
FastAPI application for SDM SQL Schema generator

2024-02-07 18:01 UTC, flopezag commented on doc/openapi.yaml
> +        - last_test_number
Add a new line at the end of the file.

2024-02-07 18:01 UTC, flopezag commented on doc/openapi.yaml
> +          description: OK
description: The service is up and running

2024-02-07 18:01 UTC, flopezag commented on doc/openapi.yaml
> +      responses:
summary: Get version information
      description: Get the correspondinf version information and the status of the service
      operationId: getVersion

2024-02-07 18:01 UTC, flopezag commented on doc/openapi.yaml
> +      summary: Generating a SQL Schema
summary: Generating a SQL Schema
  description: Generate the corresponding SQL Schema of a provided Data Model in the Smart Data Model repository
  operationId: generateSQLSchema

2024-02-07 18:01 UTC, flopezag commented on doc/openapi.yaml
> +          description: OK
description: The SQL Schema has been generated

2024-02-09 08:32 UTC, flopezag requested changes

2024-02-09 08:32 UTC, flopezag commented on README.md
> +    exit
To deactivate and exit the Poetry Virtual Environment run:

2024-02-09 08:32 UTC, flopezag commented on doc/openapi.yaml
> +      responses:
This content should be under get, not under '200'

    get:
      summary: Get version information
      description: The service is up and running
      operationId: getVersion

2024-02-12 09:53 UTC, feki-rihab commented
I just added the documentation of the service with 8 lines as you requested.

2024-02-13 08:56 UTC, feki-rihab commented on api/server.py
> +__version__ = "0.1.0"
@application.get("/version", status_code=status.HTTP_200_OK)
def getversion(request: Request):
    request.app.logger.info("GET /version - Request version information")

    data = {
        "doc": "...",
        "git_hash": "nogitversion",
        "version": **__version__**,
        "release_date": "no released",
        "uptime": get_uptime(),
    }

    return data

2024-02-13 08:56 UTC, feki-rihab commented on api/server.py
> +__version__ = "0.1.0"
it is used in the /versions api

2024-02-13 09:14 UTC, flopezag approved these changes
LGTM

2024-02-13 09:15 UTC, merged